bark:    #optional
  endpoint: https://<your-url>/<your-key/
  # default settings for other parameters
  group: "default"
  icon: "http://<your-host>/<your-default-icon.png>"
  sound: paymentsuccess
  automaticallyCopy: 0    #optional
  isArchive: 1    #optional
  url: "http://<your-url>/"    #optional
  level: active    #optional
  # tailor made parameters according to message title
  tailoring:
    - title: "example title 1"
      group: "group1"
      icon: "http://<your-host>/<your-icon-1.png>"
      sound: "calypso"
      automaticallyCopy: 0    #optional
      isArchive: 1    #optional
      url: "http://<your-url-1>/"    #optional
      level: active    #optional
    - title: "example title 2"
      group: "group2"
      icon: "http://<your-host>/<your-icon-2.png>"
      sound: "bell"
      automaticallyCopy: 0    #optional
      isArchive: 1    #optional
      url: "http://<your-url-2>/"    #optional
      level: active    #optional

serverchan:    #optional
  sckey: <your-sckey>

pushplus:    #optional
  token: <your-token>
  channel: wechat   #optional
  template: markdown    #optional

iyuu:    #optional
  token: <your-token>

smtp:    #optional
  server: <smtp-server, e.g. smtp.qq.com>
  port: 465
  sender: <sender-email, e.g. xxxx@qq.com>
  authcode: <authorization-code>
  recipient: <recipient-email, e.g. xxxx@163.com>

dingtalk:    #optional
  secret: <your-secret>
  url: <your-webhook-url>

feishu:    #optional
  secret: <your-secret>
  url: <your-webhook-url>

wxbot:    #optional
  url: <your-webhook-url>

wxapp:    #optional
  corpid: <your-corp-id>
  secret: <your-app-secret>
  agentid: <your-app-agentid>
  touser: <to-user-id>
  type: <message type, e.g. text>

telegram:    #optional
  token: <your-token>
  chatid: <your-chatid>
